#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : gradle
Version  : 6.8.3
Release  : 23
URL      : file:///aot/build/clearlinux/packages/gradle/gradle-.tar.gz
Source0  : file:///aot/build/clearlinux/packages/gradle/gradle-.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1-only MIT
BuildRequires : bash
BuildRequires : buildreq-cmake
BuildRequires : ca-certs
BuildRequires : ca-certs-static
BuildRequires : ccache
BuildRequires : curl
BuildRequires : curl-bin
BuildRequires : curl-dev
BuildRequires : curl-lib
BuildRequires : findutils
BuildRequires : mlocate
BuildRequires : openjdk13
BuildRequires : openjdk13-dev
BuildRequires : openssl-dev
BuildRequires : openssl-lib
BuildRequires : p11-kit
BuildRequires : pcre-dev
BuildRequires : pcre-extras
BuildRequires : xmlstarlet
BuildRequires : zlib-dev

%description
# Gradle for Clear Linux

%prep
%setup -q -n gradle
cd %{_builddir}/gradle

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1616444052
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$FFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$FFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1616444052
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
